services:
  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms-norte
    env_file:
      - .env
    ports:
      - "${LIBRENMS_PORT:-8000}:8000"
    volumes:
      - ./librenms:/data
    environment:
      - TZ=${TZ}
      - LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}
    depends_on:
      - mariadb
      - memcached
    networks:
      - monitor-net

  mariadb:
    image: mariadb:10.5
    container_name: librenms-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./librenms/db:/var/lib/mysql
    networks:
      - monitor-net

  memcached:
    image: memcached:alpine
    container_name: librenms-memcached
    networks:
      - monitor-net

  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: librenms-syslog-ng
    ports:
      - "514:514/udp"
    volumes:
      - ./syslog-ng:/etc/syslog-ng
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - monitor-net

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  snmp_exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
    ports:
      - "9116:9116"
    volumes:
      - ./prometheus/snmp/snmp.yml:/etc/snmp_exporter/snmp.yml
    networks:
      - monitor-net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    networks:
      - monitor-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail:/etc/promtail
    depends_on:
      - loki
    networks:
      - monitor-net

  oxidized:
    image: oxidized/oxidized:latest
    container_name: oxidized
    environment:
      - CONFIG_RELOAD_INTERVAL=3600
    volumes:
      - ./oxidized:/home/oxidized/.config/oxidized
    ports:
      - "8888:8888"
    networks:
      - monitor-net

networks:
  monitor-net:
    name: monitor-net
    driver: bridge
